all: signed.png future.png experience.png

signed.png: signed.dat graph_signed.gp
	gnuplot graph_signed.gp

future.png: future.dat graph_future.gp
	gnuplot graph_future.gp

experience.png: experience.dat graph_experience.gp
	gnuplot graph_experience.gp
